# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('item_control', models.BooleanField()),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('item_control', models.BooleanField()),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('hashid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('hasparsed', models.BooleanField(default=False)),
                ('isparseing', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=128)),
                ('parsefile', models.FileField(upload_to='workbook/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('compnay_id', models.CharField(max_length=64)),
                ('compnay_name', models.CharField(max_length=64)),
                ('group_id', models.CharField(max_length=64)),
                ('group_name', models.CharField(max_length=64)),
                ('man_id', models.CharField(max_length=32)),
                ('sub_id', models.CharField(max_length=32)),
                ('trd_id', models.CharField(max_length=32)),
                ('hashid', models.CharField(max_length=32)),
                ('traffic', models.FloatField(default=0)),
                ('income', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('gross_profit', models.FloatField(default=0)),
                ('gross_margin', models.FloatField(default=0)),
                ('profit_total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('item_control', models.BooleanField()),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxesPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxesPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hashid', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taxespayable',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='taxespayable',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='taxespaid',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='taxespaid',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='sales',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='profit',
            unique_together=set([('hashid', 'year', 'month', 'compnay_id')]),
        ),
        migrations.AlterIndexTogether(
            name='profit',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='managementcost',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='managementcost',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='laborcost',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='laborcost',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='financialexpenses',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='financialexpenses',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='depreciation',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='depreciation',
            index_together=set([('hashid', 'line', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='cost',
            unique_together=set([('hashid', 'year', 'month', 'item_id')]),
        ),
        migrations.AlterIndexTogether(
            name='cost',
            index_together=set([('hashid', 'line', 'month')]),
        ),
    ]
